name: ThunderDataEngine
version: '${project.version}'
main: net.pentlock.thunderdataengine.ThunderDataEngine
api-version: 1.19
authors: [ Pentlock, ArcticDev ]
description: Data Manager for the Thunder Ecosystem
